### ISSUE TITLE
Actividad 6 equipo 6 

### ISSUE THREAD

**Issue by ErikCuevas03** [SistemasTecTlaxiaco/actividad-6-anteproyecto-equipo-y#2]
[anteproyecto.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-anteproyecto-equipo-y/files/9748672/anteproyecto.pdf)

**Comment by josealfredo79** [comment]
Calificacion 18

**Comment by josealfredo79** [comment]
Revisado
